services:
  db:
    image: postgres:16
    container_name: calculator-db
    environment:
      POSTGRES_USER: portfolio_user
      POSTGRES_PASSWORD: h@Rp1@78579467
      POSTGRES_DB: seu_portfolio_producao_db
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    build: .
    container_name: calculator-web
    command: bin/rails server -b 0.0.0.0
    ports:
      - "8080:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: 446b58cd11a86287186837234b76c1d54e11c796f5594c4b2ccd0604a37410f326292d39d1264eed6efec7d96be1703694541064af8699421dcecd3203499792
      DATABASE_URL: postgres://portfolio_user:h%40Rp1%4078579467@db:5432/seu_portfolio_producao_db
