default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: calculadora_clt_development

test:
  <<: *default
  database: calculadora_clt_test

production:
  <<: *default
  database: calculadora_clt_production
  username: deployuser
  password: h@Rp1@78579467
  host: localhost
  port: 5434

cable:
  <<: *default
  adapter: postgresql
  database: calculadora_clt_cable
  username: deployuser
  password: h@Rp1@78579467
  host: localhost
  port: 5434

queue:
  <<: *default
  adapter: postgresql
  database: calculadora_clt_queue
  username: deployuser
  password: h@Rp1@78579467
  host: localhost
  port: 5434
  
cache:
  <<: *default
  adapter: postgresql
  database: calculadora_clt_cache
  username: deployuser
  password: h@Rp1@78579467
  host: localhost
  port: 5434
